title: Mary McEntire - Marketing Analyst
description: > # this means to ignore newlines until "baseurl:"
  Mary McEntire is a marketing professional of 5 years with an emphasis in data visualization. Her love for data has encouraged her to pursue a career as a data analyst.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mary McEntire
author-img: mary-mcentire.jpg
about-author: Marketing Analyst specializing in SEO and eCommerce strategies. I have a passion for data visualization & automation.
social-github: mkemcentire
social-linkedin: marymcentire
social-email: mke.mcentire@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: G-1D1LV0PFS2

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
